### ISSUE TITLE
use springboot lombok not working

### ISSUE THREAD

**Issue by xgaxpp** [mrclrchtr/gradle-kotlin-spring#91]
use springboot lombok not working

spring-conventions
    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")

    testCompileOnly("org.projectlombok:lombok")
    testAnnotationProcessor("org.projectlombok:lombok")

**Comment by mrclrchtr** [comment]
Hi, I don't understand your issue.. What do you want to do and what is not working? 
In my opinion, you don't need lombock at all with kotlin.

**Comment by xgaxpp** [comment]
Hi, My project uses a mix of java and kotlin, so I want to use lombok for java code. lombok didn't work properly when I enabled it.

**Comment by mrclrchtr** [comment]
I didn't have time to look for it last week. Did you make it or do you still want me to look?

**Comment by xgaxpp** [comment]
Hi, no need for now. You can also take a look if you have time. But my current goal is to get back to Kotlin development.
